version: "3.8"
services:
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    container_name: sejong-life-db
    environment:
      MYSQL_ROOT_PASSWORD: "cleancode"
      MYSQL_DATABASE: "cleancode_db"
      TZ: "Asia/Seoul"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
